### ISSUE TITLE
log_enabled config param used?

### ISSUE THREAD

**Issue by Rydgel** [sesser/Instaphp#25]
Whether or not log_enabled is set to true or false doesn't seem to impact logging. 
Looking at the source shows that monolog is always instantiated.
https://github.com/sesser/Instaphp/blob/master/src/Instaphp/Instagram/Instagram.php#L86-L87

Did I miss something?

**Comment by sesser** [comment]
Nope. Just rushed coding on my part. Feel free to fix and submit a PR.

**Comment by sesser** [comment]
This should fix it.

**Comment by Rydgel** [comment]
@sesser Thank you, much appreciated!
