### ISSUE TITLE
Class 'Monolog\Logger' not found 

### ISSUE THREAD

**Issue by xkape** [sesser/Instaphp#26]
I get this error on trying to instantiate the instaphp class. I am not using composer; Just  downloaded the source and included the php file.

**Comment by ollietb** [comment]
It's because you're not using composer. There are some dependencies on other libraries which are handled automatically when you install the package using composer.

**Comment by sesser** [comment]
Yes. I need to remove the monolog requirement for use without composer.

**Comment by sesser** [comment]
On second thought, Instaphp requires GuzzleHttp as well. Removing the dependency for either would be silly. I suggest using Composer if at all possible. Otherwise, you'll have to download the dependancies yourself and figure out the include chain to make it work.
