### ISSUE TITLE
Monolog requirement error in composer.json

### ISSUE THREAD

**Issue by kwn** [sesser/Instaphp#31]
Hi

Is there any reason to get stuck with ```1.8.*``` version? I get a conflict because other library needs at least ```1.12``` version. Or maybe instead ```1.8.*``` you meant ```~1.8```?

Could we change monolog versioning for ```~1.8```, please?

**Comment by sesser** [comment]
This should help. Let me know if it doesn't

**Comment by kwn** [comment]
@sesser Now everyhing is ok. Thanks a lot!
