### ISSUE TITLE
InvalidInstagramResponseException: The response from Instagram cannot be parsed.

### ISSUE THREAD

**Issue by bornbygoogle** [sesser/Instaphp#33]
Hi, I got this error when using instaphp through hautelook InstagramBundle

An exception has been thrown during the rendering of a template ("The response from Instagram cannot be parsed.")

[2/2] Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The response from Instagram cannot be parsed.") in index.html.twig at line 36.  +
[1/2] InvalidInstagramResponseException: The response from Instagram cannot be parsed.  -

    in C:\xampp\htdocs\Symfony\vendor\hautelook\instagram-bundle\Hautelook\InstagramBundle\Instagram\Manager.php at line 58  -
                }
                if (empty($data) || !is_array($data)) {
                    throw new InvalidInstagramResponseException();
                }
                $rawResponseData = array_slice($data, 0, min($numRecent, self::MAX_RECENT)); 

Can you please tell me what I did wrong ?

**Comment by sesser** [comment]
None of those errors/exceptions are generated by Instaphp. You'll have to talk to the folks at [hautelook](https://github.com/hautelook)
