### ISSUE TITLE
Guzzle dependency hell

### ISSUE THREAD

**Issue by chekalskiy** [sesser/Instaphp#34]
Please update Guzzle from 4 to 5. Here is instruction: https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

I'm not really sure but there is no conflicts with current code.

**Comment by lopsided** [comment]
I planned to fork and PR this change. However I had loads of failing tests even before I updated the guzzle version:

`Tests: 53, Assertions: 75, Failures: 5, Errors: 5, Incomplete: 15.` 

After updating guzzle I got the same output. I've been through the upgrade document and I can't find anything that needs changing, so I think the failing tests are unrelated to guzzle. I'm going to run with my fork for now and see if it falls over...

**Comment by chekalskiy** [comment]
@sesser what do you think?

**Comment by sesser** [comment]
I'm game. I just don't have much time at the moment. Is there a PR coming?

@lopsided, running tests against the Instagram API is a pain. I would always get errors outside my control.

**Comment by lopsided** [comment]
That's the same PR I was about to submit! My app doesn't use all of the endpoints so I can't say for sure whether all the requests still work, but the oauth and user, media and recent endpoints seem to work fine. I would be fairly confident that this PR is ok to merge.

**Comment by sesser** [comment]
I'm inclined to merge this PR, but would like to run through the upgrade to see if there's any improvements I could make elsewhere. Give me a day or two... and thanks! :+1:

**Comment by chekalskiy** [comment]
@sesser whats up?

**Comment by chekalskiy** [comment]
@sesser ;)

**Comment by sesser** [comment]
Merged

**Comment by chekalskiy** [comment]
@sesser Hello, same again with Guzzle 6 :)
