### ISSUE TITLE
Enforce signed header

### ISSUE THREAD

**Issue by maidmaid** [sesser/Instaphp#35]
Using signed headers, we can call more times certains POST endpoints. For example, ``POST /users/user-id/relationships`` endpoint without signing the limit is 20 calls per hour, with signature, we can do 60 (https://instagram.com/developer/limits/). To sign the header, here is the doc: https://instagram.com/developer/restrict-api-requests/#enforce-signed-header.

My implementation proposal:
- Add a boolean parameter ``enforce_signed_header``, ``false`` by default.
- Add a ``ips`` parameter, ``127.0.0.1`` by default.
- If ``enforce_signed_header`` is ``true``, we add a header ``Insta-X-Forwarded-For`` to request Guzzle having as value ``<ip_information>|<signature>`` as described in the documentation page.

**Comment by sesser** [comment]
Already in there. See https://github.com/sesser/Instaphp/blob/master/src/Instaphp/Instagram/Instagram.php#L140
