### ISSUE TITLE
Very big vendor-folder

### ISSUE THREAD

**Issue by drosa88** [sesser/Instaphp#38]
Hi guys,

question: do i need all the content of the created "vendor" folder? With 8MB it´s very big.. because i´m using your project to develope a wordpress plugin i have to optimize as much as possible to keep the plugin-file small.

Content of vendor folder: bin (folder), composer (folder), guzzlehttp (folder), monolog (folder), phpunit (folder), psr (folder), react (folder), symfony (folder), autoload.php
.. do i need all of this for your plugin in live-version?

Thank you very much!
Greetings

**Comment by sesser** [comment]
Probably don't need phpunit, but the folders are there for a reason. Not much you can do if you want to use this library.
