### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by igolka97** [sesser/Instaphp#48]
Hi!

When I try post or delete request, for example

    $this->instaphp->Media->Like($id);

I get fallowing errors
<img width="773" alt="2015-08-17 3 01 08" src="https://cloud.githubusercontent.com/assets/3520658/9296080/4490375a-448c-11e5-9914-0ccc576e231b.png">

Can you help me, sesser?

**Comment by sesser** [comment]
It appears your client_id is not permitted to like media items. I know there is a new-ish error being returned by the API in these cases that Instaphp is not properly catching. You also cannot comment on media items either (my client_id had this functionality revoked a while ago).
