### ISSUE TITLE
Invalid dependency

### ISSUE THREAD

**Issue by ollietb** [sesser/Instaphp#58]
I just upgraded to the latest version of instaphp and it looks like guzzlehttp/log-subscriber is not compatible with Guzzle 6

See the note from https://github.com/guzzle/log-subscriber

> [DEPRECATED AND ABANDONED] Logs HTTP requests and Responses as they are sent over the wire. Not used in Guzzle 6.

@sesser Could you revert the composer change which updated the Guzzle requirement to 6?

**Comment by ollietb** [comment]
See #47

**Comment by sesser** [comment]
Will do.

**Comment by sesser** [comment]
Merged. Thanks @ollietb
